openapi: 3.0.1
info:
  title: Hedera Account Balance Plugin
  description: A plugin that allows the user to fetch the HBAR and token balance of a Hedera account using ChatGPT.
  version: 'v1'
servers:
  - url: https://hedera-plugin-chatgpt.ed-marquez.repl.co
paths:
  /get_account_balance:
    get:
      operationId: getAccountBalance
      summary: Get the balance of a specific Hedera account
      parameters:
        - in: query
          name: account_id
          schema:
            type: string
          description: The ID of the Hedera account
        - in: query
          name: token_id
          schema:
            type: string
          description: The token ID of the HTS Token
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAccountBalanceResponse'
components:
  schemas:
    getAccountBalanceResponse:
      type: object
      properties:
        account:
          type: string
          description: The ID of the Hedera account.
        balance:
          type: number
          description: The balance of the Hedera account.
